export const CREATE_NAVIGATION_REQUEST = 'GET_CREATE_NAVIGATION_REQUEST';
export const CREATE_NAVIGATION_SUCCESS = 'GET_CREATE_NAVIGATION_SUCCESS';
export const CREATE_NAVIGATION_FAIL = 'GET_CREATE_NAVIGATION_FAIL';