export const GET_ALL_SERVICES_REQUEST = 'GET_ALL_SERVICES_REQUEST';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAIL = 'GET_ALL_SERVICES_FAIL';
export const GET_ALL_SERVICES_RESET = 'GET_ALL_SERVICES_RESET';

export const CREATE_SERVICES_REQUEST = 'CREATE_SERVICES_REQUEST';
export const CREATE_SERVICES_SUCCESS = 'CREATE_SERVICES_SUCCESS';
export const CREATE_SERVICES_FAIL = 'CREATE_SERVICES_FAIL';
export const CREATE_SERVICES_RESET = 'CREATE_SERVICES_RESET';

export const UPDATE_SERVICES_REQUEST = 'UPDATE_SERVICES_REQUEST';
export const UPDATE_SERVICES_SUCCESS = 'UPDATE_SERVICES_SUCCESS';
export const UPDATE_SERVICES_FAIL = 'UPDATE_SERVICES_FAIL';
export const UPDATE_SERVICES_RESET = 'UPDATE_SERVICES_RESET';

export const DELETE_SERVICES_REQUEST = 'DELETE_SERVICES_REQUEST';
export const DELETE_SERVICES_SUCCESS = 'DELETE_SERVICES_SUCCESS';
export const DELETE_SERVICES_FAIL = 'DELETE_SERVICES_FAIL';

export const DELETE_ALL_SERVICES_REQUEST = 'DELETE_ALL_SERVICES_REQUEST';
export const DELETE_ALL_SERVICES_SUCCESS = 'DELETE_ALL_SERVICES_SUCCESS';
export const DELETE_ALL_SERVICES_FAIL = 'DELETE_ALL_SERVICES_FAIL';