export const GET_ALL_SERVICES_REQUEST = 'GET_ALL_SERVICES_REQUEST';
export const GET_ALL_SERVICES_SUCCESS = 'GET_ALL_SERVICES_SUCCESS';
export const GET_ALL_SERVICES_FAIL = 'GET_ALL_SERVICES_FAIL';
export const GET_ALL_SERVICES_RESET = 'GET_ALL_SERVICES_RESET';